import uproot
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context('poster')

f = uproot.open("./RecoTree_GridSeed_0.1.0.root")
ftree = f.get("phaseII")
ftree.items()
fTVZ = ftree.get("trueVtxZ")
fTVY = ftree.get("trueVtxY")
fTVX = ftree.get("trueVtxX")
fPVZ = ftree.get("pointPosZ")
fPVY = ftree.get("pointPosY")
fPVX = ftree.get("pointPosX")
trueXvtx = fTVX.array()
trueZvtx = fTVZ.array()
trueYvtx = fTVY.array()
pointposXvtx = fPVX.array()
pointposZvtx = fPVZ.array()
pointposYvtx = fPVY.array()
fSVZ = ftree.get("seedVtxZ")
fSVY = ftree.get("seedVtxY")
fSVX = ftree.get("seedVtxX")
seedXvtx = fSVX.array()
seedZvtx = fSVZ.array()
seedYvtx = fSVY.array()
sns.set_style("whitegrid")
sns.axes_style("darkgrid")
xkcd_colors = ['magenta', 'black', 'slate blue', 'warm pink', 'green', 'grass']
sns.set_palette(sns.xkcd_palette(xkcd_colors))
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.plot(seedZvtx[0], seedXvtx[0], linestyle='none', 
markersize=5, label="Vertex Seeds", marker='o')
ax.plot(trueZvtx[0], trueXvtx[0], linestyle='none', 
markersize=20, label="True Vertex", marker='*')
ax.plot(pointposZvtx[0], pointposXvtx[0], linestyle='none', 
markersize=20, label="PointPosition Vertex", marker='*')
plt.ylabel("X [cm]")
plt.xlabel("Z [cm]")
leg = ax.legend(loc=2)
leg.set_frame_on(True)
leg.draw_frame(True)
plt.title("Seed generator results from simulated event")
plt.show()
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.plot(seedZvtx[0], seedYvtx[0], linestyle='none', 
markersize=5, label="Vertex Seeds", marker='o')
ax.plot(trueZvtx[0], trueYvtx[0], linestyle='none', 
markersize=20, label="True Vertex", marker='*')
ax.plot(pointposZvtx[0], pointposYvtx[0], linestyle='none', 
markersize=20, label="PointPosition Vertex", marker='*')
plt.ylabel("Y [cm]")
plt.xlabel("Z [cm]")
leg = ax.legend(loc=2)
leg.set_frame_on(True)
leg.draw_frame(True)
plt.title("Seed generator results from simulated event")
plt.show()
